[project]
name = "zk_implementation"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    # "onnx>=1.21.0",
    # "torch>=2.11.0",
    # "transformers>=5.7.0",
    "onnx>=1.15.0",
    "torch>=2.1.0",
    "transformers==4.37.0",
    "onnxruntime>=1.25.1",
    "onnxscript>=0.7.0",
    "runtime>=0.1.4",
]

[dependency-groups]
dev = [
    "onnxruntime>=1.25.1",
]
